[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
testnet = "${TESTNET_RPC_URL}"

[etherscan]
mainnet = { key = "${MAINNET_ETHERSCAN_API_KEY}", url = "${MAINNET_ETHERSCAN_API_URL}" }
testnet = { key = "${TESTNET_ETHERSCAN_API_KEY}", url = "${TESTNET_ETHERSCAN_API_URL}" }
